S = set()
S.add(int(input("Number: ")))
S.add(int(input("Number: ")))
S.add(int(input("Number: ")))
S.add(int(input("Number: ")))
S.add(int(input("Number: ")))
S.add(int(input("Number: ")))
S.add(int(input("Number: ")))
S.add(int(input("Number: ")))
S.add((input("Number: ")))
print(S)
