list = []
list.append(input("Enter Fruit: "))
print(list)
list.append(input("Enter Fruit: "))
print(list)
list.append(input("Enter Fruit: "))
print(list)
list.append(input("Enter Fruit: "))
print(list)
list.append(input("Enter Fruit: "))
print(list)
list.append(input("Enter Fruit: "))
print(list)
list.append(input("Enter Fruit: "))
print(list)