marks = []
marks.append(input("Marks: "))
print(marks)
marks.append(input("Marks: "))
print(marks)
marks.append(input("Marks: "))
print(marks)
marks.append(input("Marks: "))
print(marks)
marks.append(input("Marks: "))
print(marks)
marks.append(input("Marks: "))
print(marks)
marks.sort()
print(marks)